version: '2'

services:

    postgres:
        container_name: quotata-db
        build:
            context: postgres
        ports:
            - 5432:5432
        volumes:
            - s_database:/var/lib/postgresql/data
            - ./var/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: ${DOCKER_DB_USER}
            POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
            POSTGRES_DB: ${DOCKER_DB_NAME}
            PGDATA: /var/lib/postgresql/data/pgdata

    php:
        container_name: quotata-php
        build:
            context: php
            args:
                HOST_USER_ID: ${DOCKER_USER_ID}
                HOST_GROUP_ID: ${DOCKER_GROUP_ID}
        volumes:
            - ${DOCKER_APP_PATH}:/var/www:cached

    nginx:
        container_name: quotata-nginx
        build:
            context: nginx
            args:
                HOST_USER_ID: ${DOCKER_USER_ID}
                HOST_GROUP_ID: ${DOCKER_GROUP_ID}
        ports:
            - 8080:80
        volumes_from:
            - php

    frontend:
        container_name: quotata-frontend
        restart: 'no'
        user: "${DOCKER_USER_ID}:${DOCKER_GROUP_ID}"
        build:
            context: frontend
        volumes:
            - ${DOCKER_APP_PATH}:/var/www:cached

volumes:
    s_database:
